// CampusBite PSGCAS Complete Master Data
// Provides rich South Indian campus food items, categories, demo users, and offline fallback

export const CATEGORIES = [
  { id: "all", key: "all", label: "All Items", icon: "🍽️" },
  {
    id: "breakfast",
    key: "breakfast",
    label: "Breakfast",
    tagline: "Start fresh • Traditional favourites to start your day right",
    icon: "🥞",
    image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: "lunch",
    key: "lunch",
    label: "Lunch",
    tagline: "Wholesome meals • Nourishing afternoon meals",
    icon: "🍛",
    image: "https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: "snacks",
    key: "snacks",
    label: "Snacks",
    tagline: "Quick bites • Hot & crispy canteen snacks",
    icon: "🥟",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: "juice",
    key: "juice",
    label: "Juice",
    tagline: "Fresh & healthy • 100% pure cold pressed juices",
    icon: "🍹",
    image: "https://images.unsplash.com/photo-1613478223719-2ab802602423?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: "chat",
    key: "chat",
    label: "Chaat Items",
    tagline: "Full of flavour • Spicy tangy street favourites",
    icon: "🥣",
    image: "https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: "icecream",
    key: "icecream",
    label: "Ice Cream",
    tagline: "Cool your day • Creamy desserts & cones",
    icon: "🍦",
    image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=600&auto=format&fit=crop&q=80",
  },
];

export const INITIAL_FOODS = [
  // BREAKFAST
  {
    id: 1,
    name: "Idli Sambar",
    category: "breakfast",
    category_name: "Breakfast",
    price: 30,
    description: "Soft steaming hot idlis served with flavourful Madras sambar and fresh coconut chutney.",
    image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&auto=format&fit=crop&q=80",
    image_url: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&auto=format&fit=crop&q=80",
    preparation_time: 5,
    is_available: true,
    rating: 4.8,
  },
  {
    id: 2,
    name: "Masala Dosa",
    category: "breakfast",
    category_name: "Breakfast",
    price: 50,
    description: "Crispy golden South Indian dosa stuffed with spiced potato masala, served with 2 chutneys & sambar.",
    image: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=600&auto=format&fit=crop&q=80",
    image_url: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=600&auto=format&fit=crop&q=80",
    preparation_time: 8,
    is_available: true,
    rating: 4.9,
  },
  {
    id: 3,
    name: "Pongal",
    category: "breakfast",
    category_name: "Breakfast",
    price: 40,
    description: "Hot ghee ven pongal infused with roasted cashews, black pepper, cumin, with chutney & sambar.",
    image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=600&auto=format&fit=crop&q=80",
    image_url: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=600&auto=format&fit=crop&q=80",
    preparation_time: 5,
    is_available: true,
    rating: 4.7,
  },
  {
    id: 4,
    name: "Poori Set",
    category: "breakfast",
    category_name: "Breakfast",
    price: 40,
    description: "Two fluffy puffed pooris served with authentic potato masala and onion gravy.",
    image: "https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=600&auto=format&fit=crop&q=80",
    image_url: "https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=600&auto=format&fit=crop&q=80",
    preparation_time: 8,
    is_available: true,
    rating: 4.6,
  },
  {
    id: 5,
    name: "Filter Coffee",
    category: "breakfast",
    category_name: "Breakfast",
    price: 25,
    description: "Authentic Kumbakonam degree filter coffee brewed strong with frothy full-cream milk.",
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80",
    image_url: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80",
    preparation_time: 3,
    is_available: true,
    rating: 5.0,
  },

  // LUNCH
  {
    id: 6,
    name: "Special South Indian Meals",
    category: "lunch",
    category_name: "Lunch",
    price: 90,
    description: "Complete wholesome college meal: Rice, Sambar, Rasam, Kara Kuzhambu, Poriyal, Kootu, Appalam & Curd.",
    image: "https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?w=600&auto=format&fit=crop&q=80",
    image_url: "https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?w=600&auto=format&fit=crop&q=80",
    preparation_time: 10,
    is_available: true,
    rating: 4.9,
  },
  {
    id: 7,
    name: "Veg Fried Rice",
    category: "lunch",
    category_name: "Lunch",
    price: 65,
    description: "Wok-tossed basmati rice with crunchy garden veggies, spring onion, and mild oriental spices.",
    image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&auto=format&fit=crop&q=80",
    image_url: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&auto=format&fit=crop&q=80",
    preparation_time: 10,
    is_available: true,
    rating: 4.7,
  },
  {
    id: 8,
    name: "Sambar Rice with Appalam",
    category: "lunch",
    category_name: "Lunch",
    price: 55,
    description: "Comforting ghee sambar sadham served hot with crispy appalam and lemon pickle.",
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&auto=format&fit=crop&q=80",
    image_url: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&auto=format&fit=crop&q=80",
    preparation_time: 5,
    is_available: true,
    rating: 4.6,
  },
  {
    id: 9,
    name: "Curd Rice",
    category: "lunch",
    category_name: "Lunch",
    price: 45,
    description: "Cooling creamy curd rice tempered with mustard, curry leaves, ginger, pomegranate and pickle.",
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&auto=format&fit=crop&q=80",
    image_url: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&auto=format&fit=crop&q=80",
    preparation_time: 3,
    is_available: true,
    rating: 4.8,
  },

  // SNACKS
  {
    id: 10,
    name: "Crispy Samosa (2 pcs)",
    category: "snacks",
    category_name: "Snacks",
    price: 25,
    description: "Golden flaky pastry stuffed with savoury spiced potatoes, peas, served with sweet & mint chutney.",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600&auto=format&fit=crop&q=80",
    image_url: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600&auto=format&fit=crop&q=80",
    preparation_time: 4,
    is_available: true,
    rating: 4.8,
  },
  {
    id: 11,
    name: "Grilled Veg Sandwich",
    category: "snacks",
    category_name: "Snacks",
    price: 45,
    description: "Toasted bread layered with crisp cucumber, tomatoes, cheese slice and tangy mint spread.",
    image: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=600&auto=format&fit=crop&q=80",
    image_url: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=600&auto=format&fit=crop&q=80",
    preparation_time: 8,
    is_available: true,
    rating: 4.7,
  },
  {
    id: 12,
    name: "Crispy French Fries",
    category: "snacks",
    category_name: "Snacks",
    price: 50,
    description: "Golden salted potato fries seasoned with peri-peri sprinkle and served with tomato dip.",
    image: "https://images.unsplash.com/photo-1576107232684-1279f3908594?w=600&auto=format&fit=crop&q=80",
    image_url: "https://images.unsplash.com/photo-1576107232684-1279f3908594?w=600&auto=format&fit=crop&q=80",
    preparation_time: 6,
    is_available: true,
    rating: 4.5,
  },

  // JUICE
  {
    id: 13,
    name: "Fresh Orange Juice",
    category: "juice",
    category_name: "Juice",
    price: 40,
    description: "Freshly squeezed sweet oranges without artificial preservatives, rich in Vitamin C.",
    image: "https://images.unsplash.com/photo-1613478223719-2ab802602423?w=600&auto=format&fit=crop&q=80",
    image_url: "https://images.unsplash.com/photo-1613478223719-2ab802602423?w=600&auto=format&fit=crop&q=80",
    preparation_time: 4,
    is_available: true,
    rating: 4.9,
  },
  {
    id: 14,
    name: "Watermelon Cooler",
    category: "juice",
    category_name: "Juice",
    price: 35,
    description: "Refreshing cold watermelon juice with a hint of fresh mint and black salt.",
    image: "https://images.unsplash.com/photo-1589733955941-5eeaf752f6dd?w=600&auto=format&fit=crop&q=80",
    image_url: "https://images.unsplash.com/photo-1589733955941-5eeaf752f6dd?w=600&auto=format&fit=crop&q=80",
    preparation_time: 3,
    is_available: true,
    rating: 4.8,
  },

  // CHAT ITEMS
  {
    id: 15,
    name: "Pani Puri (6 pcs)",
    category: "chat",
    category_name: "Chaat Items",
    price: 40,
    description: "Crisp puris loaded with spiced potato filling, dipped in chilled spicy mint & sweet tamarind water.",
    image: "https://images.unsplash.com/photo-1601050690113-92f75ba315e7?w=600&auto=format&fit=crop&q=80",
    image_url: "https://images.unsplash.com/photo-1601050690113-92f75ba315e7?w=600&auto=format&fit=crop&q=80",
    preparation_time: 5,
    is_available: true,
    rating: 5.0,
  },
  {
    id: 16,
    name: "Bhel Puri",
    category: "chat",
    category_name: "Chaat Items",
    price: 45,
    description: "Puffed rice tossed with raw onions, roasted peanuts, sev, and sweet-sour chutneys.",
    image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=600&auto=format&fit=crop&q=80",
    image_url: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=600&auto=format&fit=crop&q=80",
    preparation_time: 5,
    is_available: true,
    rating: 4.6,
  },

  // ICE CREAM
  {
    id: 17,
    name: "Belgian Chocolate Scoop",
    category: "icecream",
    category_name: "Ice Cream",
    price: 50,
    description: "Rich and creamy dark chocolate ice cream topped with chocolate chips and fudge drizzle.",
    image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=600&auto=format&fit=crop&q=80",
    image_url: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=600&auto=format&fit=crop&q=80",
    preparation_time: 2,
    is_available: true,
    rating: 4.9,
  },
  {
    id: 18,
    name: "Butterscotch Delight",
    category: "icecream",
    category_name: "Ice Cream",
    price: 50,
    description: "Velvety butterscotch ice cream with caramel crunchies and roasted cashews.",
    image: "https://images.unsplash.com/photo-1501443762994-82bd5dace89a?w=600&auto=format&fit=crop&q=80",
    image_url: "https://images.unsplash.com/photo-1501443762994-82bd5dace89a?w=600&auto=format&fit=crop&q=80",
    preparation_time: 2,
    is_available: true,
    rating: 4.8,
  },
];

export const DEMO_USERS = {
  student: {
    id: 3,
    username: "akash",
    fullName: "Akash R.",
    email: "akash.bcs@psgcas.ac.in",
    role: "student",
    rollNumber: "23BCS042",
    department: "B.Sc Computer Science",
    avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=120&auto=format&fit=crop&q=80",
    token: "cb-token-demo-student",
  },
  teacher: {
    id: 4,
    username: "teacher",
    fullName: "Dr. Priya V.",
    email: "priya.cs@psgcas.ac.in",
    role: "teacher",
    rollNumber: "FAC-8842",
    department: "Dept of Computer Science",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80",
    token: "cb-token-demo-teacher",
    designation: "Associate Professor",
  },
  admin: {
    id: 1,
    username: "admin",
    fullName: "Food Court Admin",
    email: "admin.foodcourt@psgcas.ac.in",
    role: "admin",
    rollNumber: "ADM-001",
    department: "Canteen Operations",
    token: "cb-token-demo-admin",
  },
  kitchen: {
    id: 2,
    username: "kitchen",
    fullName: "Master Chef Murugan",
    email: "kitchen.kds@psgcas.ac.in",
    role: "kitchen",
    rollNumber: "KDS-005",
    department: "Main Food Court Kitchen",
    token: "cb-token-demo-kitchen",
  },
};

// Seed live kitchen queue matching Screen 14 of design
export const INITIAL_KITCHEN_ORDERS = [
  { id: 32, orderNum: "032", item: "Masala Dosa", time: "10:24 AM", status: "pending", customer: "Akash R.", qty: 1 },
  { id: 33, orderNum: "033", item: "Idli Sambar", time: "10:26 AM", status: "pending", customer: "Dr. Priya", qty: 2 },
  { id: 34, orderNum: "034", item: "Veg Fried Rice", time: "10:27 AM", status: "preparing", customer: "Sanjay K.", qty: 1 },
  { id: 35, orderNum: "035", item: "Sandwich", time: "10:28 AM", status: "preparing", customer: "Meera S.", qty: 2 },
  { id: 36, orderNum: "036", item: "Pongal", time: "10:30 AM", status: "pending", customer: "Rahul M.", qty: 1 },
  { id: 37, orderNum: "037", item: "Filter Coffee", time: "10:31 AM", status: "ready", customer: "Dr. Priya", qty: 2 },
  { id: 38, orderNum: "038", item: "French Fries", time: "10:32 AM", status: "preparing", customer: "Kavya P.", qty: 1 },
  { id: 39, orderNum: "039", item: "Ice Cream", time: "10:33 AM", status: "pending", customer: "Vignesh T.", qty: 1 },
];
