import { Link, useLocation, useNavigate } from "react-router-dom";
import { motion } from "framer-motion";
import { FaUtensils, FaUserShield, FaUserGraduate, FaChalkboardTeacher, FaExchangeAlt, FaShoppingCart, FaHome, FaClipboardList } from "react-icons/fa";
import { useAuth } from "../context/AuthContext";
export default function Navbar({ cartCount = 0 }) {
 const { user, role, openLoginModal, isAdmin, isKitchen, logout } = useAuth();
 const location = useLocation();
 const navigate = useNavigate();
 const RoleIcon = role === 'admin' ? FaUserShield : role === 'kitchen' ? FaUtensils : role === 'teacher' ? FaChalkboardTeacher : FaUserGraduate;
 const roleLabel = role === 'admin' ? 'Admin' : role === 'kitchen' ? 'Kitchen' : role === 'teacher' ? 'Teacher' : 'Student';
 const active = path => location.pathname === path ? 'active' : '';
 return <><div className="top-bar-replica"><div className="top-bar-content"><div className="top-college-crest"><img src="/campusbite-logo.jpeg" alt="CampusBite PSGCAS Food Court logo" className="crest-mini-img" /><span>PSG College of Arts & Science · Autonomous Institution</span></div><div className="top-bar-right"><span className="motto-tag">Good Food · Brighter Days</span><button className="role-switch-btn" onClick={openLoginModal}><FaExchangeAlt /> Portal: <strong>{roleLabel}</strong></button></div></div></div>
 <nav className="navbar-replica" aria-label="Main navigation"><div className="navbar-container"><Link to="/" className="brand-link"><div className="brand"><motion.div className="logo-box" whileHover={{scale:1.05}} transition={{duration:.2}}><img src="/campusbite-logo.jpeg" alt="CampusBite PSGCAS Food Court logo" className="brand-logo-img" /></motion.div><div className="brand-text"><h2>Campus<span>Bite</span></h2><p>PSG College of Arts & Science Food Court</p></div></div></Link><div className={`desktop-nav-links ${location.pathname === "/" ? "outline-home-nav" : ""}`}><Link to="/menu" className={active('/menu')}>Menu</Link><Link to="/teacher" className={`portal-link teacher-link ${active('/teacher')}`}><FaChalkboardTeacher /> Teacher Lounge</Link>{isAdmin && <Link to="/admin" className={`portal-link admin-link ${active('/admin')}`}><FaUserShield /> Admin Panel</Link>}{isKitchen && <Link to="/kitchen" className={`portal-link kitchen-link ${active('/kitchen')}`}><FaUtensils /> Kitchen KDS</Link>}<Link to="/cart" className={`cart-link-btn ${active('/cart')}`}><FaShoppingCart /><span>Cart</span>{cartCount > 0 && <span className="cart-badge">{cartCount}</span>}</Link><Link to="/orders" className={active('/orders')}>Orders</Link><motion.button className={`user-role-pill ${role}`} onClick={openLoginModal} whileHover={{scale:1.03}} whileTap={{scale:.97}} title="Click to switch role or login"><RoleIcon className="role-badge-icon" /><div className="user-pill-text"><span className="user-name">{user?.fullName || user?.username}</span><span className="user-role-label">{roleLabel}</span></div></motion.button></div></div></nav>
 {location.pathname !== "/" && <div className="mobile-bottom-nav"><Link to="/portals" className={`bottom-nav-item ${active('/portals')}`}><FaHome /><span>Portals</span></Link><Link to="/menu" className={`bottom-nav-item ${active('/menu')}`}><FaUtensils /><span>Menu</span></Link><Link to="/cart" className={`bottom-nav-item cart-item ${active('/cart')}`}><div className="cart-icon-wrap"><FaShoppingCart />{cartCount > 0 && <span className="bottom-cart-badge">{cartCount}</span>}</div><span>Cart</span></Link><Link to="/orders" className={`bottom-nav-item ${active('/orders')}`}><FaClipboardList /><span>Orders</span></Link><button className="bottom-nav-item profile-item" onClick={openLoginModal}><RoleIcon className="role-badge-icon" /><span>{roleLabel}</span></button></div>}</>;
}
