import { Link, useSearchParams } from "react-router-dom";
import ReceiptBarcode from "../components/ReceiptBarcode";
import { readStored } from "../api/receipts";
export default function Bill({ lastOrder }) {
 const [params]=useSearchParams();
 const requested=params.get('id');
 const receipts=readStored('campusbite_receipts',[]);
 const order=requested ? receipts.find(r=>r.id===requested) : readStored('lastOrder',null) || lastOrder;
 if (!order) return <main className="bill-invoice-page"><h1>No bill found</h1><p>Complete an order to generate your bill. Saved bills are available in this browser.</p><Link to="/menu">Browse menu →</Link></main>;
 const money=value=>Number(value ?? 0).toFixed(2);
 return <main className="bill-invoice-page"><div className="invoice-container"><div className="invoice-nav-row"><h1>Order bill</h1></div><article className="invoice-card-replica printable-receipt"><div className="college-bill-branding"><img src="/campusbite-logo.jpeg" alt="CampusBite logo" className="invoice-college-logo" /><div><h2>CampusBite</h2><p>PSG College of Arts & Science</p><p>Food Court · Coimbatore</p></div></div><div className="invoice-meta-header"><strong>Bill ID</strong><code>{order.id}</code></div><div className="customer-pickup-details"><p><strong>Name:</strong> {order.customerName}</p><p><strong>Date:</strong> {order.orderDate}</p><p><strong>Time:</strong> {order.orderTime} IST</p><p><strong>Pickup:</strong> {order.pickupTime}</p><p><strong>Payment:</strong> UPI · {order.paymentStatus || 'Awaiting verification'}</p>{order.transactionReference && <p><strong>UPI reference:</strong> {order.transactionReference}</p>}</div><table className="invoice-items-table"><thead><tr><th>Food name</th><th>Qty</th><th>Unit price</th><th>Amount</th></tr></thead><tbody>{order.items.map((item,index)=><tr key={index}><td>{item.name}</td><td>{item.quantity}</td><td>₹{money(item.price)}</td><td>₹{money(Number(item.price)*item.quantity)}</td></tr>)}</tbody></table><div className="invoice-totals-breakdown"><div className="line-row"><span>Subtotal</span><span>₹{money(order.subtotal)}</span></div><div className="line-row"><span>CGST (2.5%)</span><span>₹{money(order.cgst)}</span></div><div className="line-row"><span>SGST (2.5%)</span><span>₹{money(order.sgst)}</span></div><div className="line-row grand-total"><strong>Total</strong><strong>₹{money(order.total)}</strong></div></div><ReceiptBarcode value={order.id} /><p className="payment-verification-note">Payment must be verified by staff before handover. A barcode identifies the order; it is not proof of payment.</p><div className="invoice-footer-message">Thank you! Good Food. Brighter Days.</div></article><div className="invoice-action-buttons"><button className="action-btn" onClick={()=>window.print()}>Print / Save PDF</button><Link className="action-btn" to="/orders">Track order</Link><Link className="action-btn" to="/menu">Order again</Link></div>{receipts.length>1 && <details className="receipt-history"><summary>Previous bills ({receipts.length})</summary>{receipts.map(r=><Link key={r.id} to={`/bill?id=${r.id}`}>{r.orderDate} · {r.customerName} · ₹{money(r.total)} · {r.id}</Link>)}</details>}</div></main>;
}
